# permissions for end users to view mysqlclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mysql-crd
    app.kubernetes.io/managed-by: kustomize
  name: mysqlcluster-viewer-role
rules:
- apiGroups:
  - db.my.domain
  resources:
  - mysqlclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.my.domain
  resources:
  - mysqlclusters/status
  verbs:
  - get
