apiVersion: db.my.domain/v1
kind: MySQLCluster
metadata:
  labels:
    app.kubernetes.io/name: mysql-crd
    app.kubernetes.io/managed-by: kustomize
  name: mysqlcluster-sample
spec:
  # TODO(user): Add fields here
        replicas: 1
